name: Deploy
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout
      - name: Setup Node
        uses: actions/setup-node
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        uses: bahmutov/npm-install@v1
      - name: Print TypeScript version
        run: npx tsc --version
      - name: Build project
        env:
          VITE_API_URL: ${{ secrets.VITE_API_URL }}
        run: npm run build
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v4
        with:
          name: production-files
          path: ./dist
  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: production-files
          path: ./dist
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist